# Generated by Django 5.1.6 on 2025-02-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrequest',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
