# Generated by Django 5.1.6 on 2025-03-01 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservationrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrequest',
            name='duration',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
